# Generated by Django 2.2.5 on 2022-01-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20220117_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
