# Generated by Django 3.2.5 on 2022-02-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
